name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build backend
        working-directory: backend
        run: |
          npm ci || npm i
          node -e "console.log('skip build step for backend')"

      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm ci || npm i
          npm run build
